### ISSUE TITLE
式の評価時にCellを更新しないようにしたい

### ISSUE THREAD

**Issue by puu123** [mygreen/excel-cellformatter#17]
大変有益なソフトウェアの公開ありがとうございます。
いきなりの要望で申し訳ありません。

POICellFormatter.getFormulaCellValueメソッドの中で
FormulaEvaluator.evaluateInCellメソッドを使用されていますが、
本メソッドはCellの更新伴うもののようですね。

可能であれば、元のCellの情報を変更したり失うことなしに
読み込みを済ませたいときもあるかと思うのですが、
いかがでしょうか。

**Comment by mygreen** [comment]
- ``FormulaEvaluator.evaluate(cell)`` を利用して、セルの値を更新しないようにしました。
- v0.8.3 として修正を取り込み、リリースしました。
